name: Build and Test app
on: push
jobs:
  build:
    runs-on: macos-latest
    env:
      XC_VERSION: ${{ '13.4.1' }}
      XC_WORKSPACE: ${{ 'SampleApp.xcodeproj' }}
      XC_SCHEME: ${{ 'SampleApp' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode.app"
    - uses: actions/checkout@v2
    - name: Run Unit and UI Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 13'